name: novelcovid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  intl: ^0.16.1
  html_color: ^1.0.1
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  share: ^0.6.3+6
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/COVIDweb_02_bed.png
    - assets/images/COVIDweb_05_mask.png
    - assets/images/COVIDweb_06_coverCough.png
    - assets/images/COVIDweb_09_clean.png
    - assets/images/protect-quarantine.png
    - assets/images/protect_wash_hands.png
    - assets/images/COVIDweb_04_CallDoc.png
    - assets/images/COVIDweb_07_wash.png
    - assets/images/COVIDweb_08_DontShare.png
    - assets/images/COVIDweb_10_temperature.png
    - assets/images/COVIDweb_12_endQuar2.png
    - assets/images/COVIDweb_03_separate.png
    - assets/images/myths/myths.png
    - assets/images/myths/china_importing.png
    - assets/images/myths/adequate_water.png
    - assets/images/myths/alcohol.png
    - assets/images/myths/antibiotic.png
    - assets/images/myths/bank_note.png
    - assets/images/myths/bazir_smoke.png
    - assets/images/myths/bed_cleaner.png
    - assets/images/myths/by_air.png
    - assets/images/myths/drink_alcohol.png
    - assets/images/myths/empty_sanitizer.png
    - assets/images/myths/germ_killer.png
    - assets/images/myths/hand_drier.png
    - assets/images/myths/infection_animal.png
    - assets/images/myths/mosqueto_infection.png
    - assets/images/myths/newmonia.png
    - assets/images/myths/risk_young.png
    - assets/images/myths/salline.png
    - assets/images/myths/smoke.png
    - assets/images/myths/treatment.png
    - assets/images/myths/ultra_ray.png
    - assets/images/myths/warm_condition.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
